DentalAppointments/Models/DentalAppointmentModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DentalAppointments.Models
{
    [Serializable]
    public class DentalAppointmentModel
    {
        [Display(Name = "Start Time")]
        public DateTime StartTime { get; set; }

        [Display(Name = "End Time")]
        public DateTime EndTime { get; set; }

        [Required]
        [Display(Name = "Dentist Name")]
        public string DentistName { get; set; }

        [Required]
        [Display(Name = "Patient Name")]
        public string PatientName { get; set; }
 
    }
}

DentalAppointments/Models/ErrorViewModel.cs
using System;

namespace DentalAppointments.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DentalAppointments/Controllers/DentalApptController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DentalAppointments.Models;
using DentalAppointments.ExtensionMethods;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Newtonsoft.Json;

namespace DentalAppointments.Controllers
{ 
    public class DentalApptController : Controller
    {
        

        public IActionResult Index()
        {
            return View(DentalAppointmentLst);
        }

        [HttpGet]
        public IActionResult Create()
        {
            DateTime startTime = DateTime.Now;
            startTime = startTime.AddSeconds(-startTime.Second);

            var newDentalAppointment = new DentalAppointmentModel
            {
                StartTime = DateTime.Now.TruncateToMinute(),
                EndTime = DateTime.Now.TruncateToMinute() 
            }; 

            return View("Create", newDentalAppointment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(DentalAppointmentModel newDentalAppointment)
        {
            if (ModelState.IsValid)
            {
                var errorFlag = false;
                var errorMsg = string.Empty;
                var doesAppointmentOverlap = DoesAppointmentOverlap(newDentalAppointment);
                TimeSpan duration = newDentalAppointment.EndTime - newDentalAppointment.StartTime;

                if (doesAppointmentOverlap)
                {
                    errorFlag = true;
                    errorMsg += " (*) Appointment with the dentist for that start time exists. ";
                }

                if (newDentalAppointment.StartTime <= DateTime.Now)
                {
                    errorFlag = true;
                    errorMsg += " (*) Appointment must be in the future. ";
                }

                if (duration.TotalMinutes < 30)
                {
                    errorFlag = true;
                    errorMsg += " (*) Appointment must be at least 30 minutes. ";
                }

                TempData["errormessage"] = errorMsg;

                if (!errorFlag)
                {
                    AddDentalAppointment(newDentalAppointment);

                    TempData["Message"] = "Added New Appointment";
                    return RedirectToAction("Index");
                }
            } 
            return View("Create", newDentalAppointment);
        }

        private List<DentalAppointmentModel> _dentalAppointmentLst = null;
        private const string DentalAppointmentLstObgName = "DentalAppointmentLst";

        private bool DoesAppointmentOverlap(DentalAppointmentModel newDentalAppointment)
        {
            var dentalAppt = DentalAppointmentLst.Find(x => x.DentistName == newDentalAppointment.DentistName
                && x.StartTime == newDentalAppointment.StartTime);

            return (dentalAppt != null);
        }

        private void AddDentalAppointment(DentalAppointmentModel newDentalAppointment)
        {
            DentalAppointmentLst.Add(newDentalAppointment);

            TempData.Put(DentalAppointmentLstObgName, DentalAppointmentLst);
             
        }

        private List<DentalAppointmentModel> DentalAppointmentLst
        {
            get
            {
                if (_dentalAppointmentLst == null)
                {
                    if (TempData[DentalAppointmentLstObgName] != null)
                    {
                        _dentalAppointmentLst = TempData.Get<List<DentalAppointmentModel>>(DentalAppointmentLstObgName);

                        TempData.Put(DentalAppointmentLstObgName, _dentalAppointmentLst);
                    }
                    else
                    {
                        _dentalAppointmentLst = new List<DentalAppointmentModel>();
                    }
                }
                return _dentalAppointmentLst;
            }
        }
    }
}

DentalAppointments/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DentalAppointments.Models;

namespace DentalAppointments.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DentalAppointments/Views/DentalAppt/Create.cshtml
@model DentalAppointments.Models.DentalAppointmentModel
@{
    ViewData["Title"] = "Create";
}

@section scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

 
<h2>Create Appointment</h2>
<form asp-action="Create"  >
    <div class="form-group form-group-sm">
        <label class="control-label">Dentist Name</label>
        <input asp-for="DentistName" class="form-control" width="250" />
        <span asp-validation-for="DentistName" class="text-danger"></span>
    </div>
    <div class="form-group form-group-sm">
        <label class="control-label">Patient Name</label>
        <input asp-for="PatientName" class="form-control" width="250" />
        <span asp-validation-for="PatientName" class="text-danger"></span>
    </div>
    <div class="form-group form-group-sm">
        <label>Choose a start time for your appointment:</label>
        <input type="datetime-local"
               min="2019-06-07T00:00"  
               asp-for="StartTime">

        <span asp-validation-for="StartTime" class="text-danger"></span>
    </div>
    <div class="form-group form-group-sm">
        <label>Choose a end time for your appointment:</label>
        <input type="datetime-local"
               min="2019-06-07T00:00"  
               asp-for="EndTime">

        <span asp-validation-for="EndTime" class="text-danger"></span>
    </div>

    <br />
    <br />
    <div class="form-group">
        <input type="submit" value="Add Appointment"   />
    </div>
    </form>
    @*value="2018-06-12T19:30"*@

DentalAppointments/Views/DentalAppt/Index.cshtml
@model IEnumerable<DentalAppointments.Models.DentalAppointmentModel>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StartTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DentistName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PatientName)
            </th> 
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StartTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DentistName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PatientName)
            </td>
             
        </tr>
}
    </tbody>
</table>

DentalAppointments/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

DentalAppointments/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DentalAppointments/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

DentalAppointments/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DentalAppointments</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="DentalAppt" asp-action="Index" class="navbar-brand">Dental Appointments</a>
            </div>
            @*<div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"> 
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>*@
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @{
            if (@TempData.Peek("message") != null)
            {
                <span style="font-size: 18px;color:Green" id="MESSAGE_TOP">
                    @TempData["message"]
                </span>
            } }

        @{
            if (@TempData.Peek("errormessage") != null)
            {
                <span style="font-size: 18px;" id="MESSAGE_TOP" class="text-danger">
                    @TempData["errormessage"]
                </span>
            } }

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - DentalAppointments</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

         
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>